import math
import itertools
import time
import numpy as np                      # this needs to be installed using sudo apt install python3-numpy or pip install numpy

# Constants ---------------------------------------------------------------

totalItems = 450000
falsePositiveRate = 0.01

# ------------------------------------------------------------------------- 

def get_h1(sha_string):                 # take first half of sha string and return as integer. usage: firstHalf = get_h1(sha_string)
    midpoint = len(sha_string) // 2
    first_half = sha_string[:midpoint] # split in python [beginning_of_split:end_of_split]

    return int(first_half, 16)          # converts hexadecimal number to decimal number and returns

def get_h2(sha_string):                 # take second half of sha string and return as integer. usage: secondHalf = get_h2(sha_string)
    midpoint = len(sha_string) // 2
    last_half = sha_string[midpoint:]

    return int(last_half, 16)           # converts hexadecimal number to decimal number and returns

def generate_indices(sha_string, m, k): # makes a list of k hashes of a password. usage: indices = generate_indicies(sha_string, m, k)
    h1 = get_h1(sha_string)
    h2 = get_h2(sha_string)

    indices = []    # empty list to add our indices calcukated inside

    for i in range(k):
        raw_hash = h1 + (i * h2)    #calculate raw hash based on double hash formula
        final_index = raw_hash % m  #apply mod to ensure index fits inside bit array
        indices.append (final_index)    #add index to list
    return indices

def sizeFilter(n, p):                   # calculate m = number of bits in array, k = number of hash functions and return. usage: m, k = sizeFilter(number of items to insert, false positive rate)
    m = math.ceil((-n * math.log(p)) / (math.log(2) ** 2))
    k = math.ceil((m/n) * math.log(2))
    return m, k

def readData(filename):                 # read from file and puts every new line into an array. usage: array = readData(filename)
    with open(filename, 'r') as file:
        dataArray = [line.strip() for line in file]

    return dataArray

def insert(bitArray, m, k, sha_string):   # call generate indices, and flip bit positions to 1. usage: insert(bitArray, m, k, sha string)
    positionsToFlip = generate_indices(sha_string, m, k)

    for i in positionsToFlip:
         bitArray[i] = 1

def query(bitArray, m, k, sha_string): # search if indices generated by password has bits flipped to 1, if all bits are 1 return true, if not return false. usage: query(bitArray, m, k, sha string)
    positionsToCheck = generate_indices(sha_string, m, k)

    for i in positionsToCheck:
        if bitArray[i] == 1:
            continue
        else:
            return False
    return True

def queryTime(m, k, n, hexPasswords, bitArray, offset): # queries the bitArray with the passwords, returns amount of trues. usage: trues, time = queryTime(m, k, n, hexPasswords, bitArray, offset) 
    Trues = 0
    avgTime = 0

    for i  in range(n):
        start = time.perf_counter()
        if query(bitArray, m, k, hexPasswords[i + offset]) == True:
            Trues += 1
        if i % 1000 == 0 and i != 0:
            end = time.perf_counter()
            avgTime += (end - start) * 1000
    
    return Trues, avgTime / (n / 1000)

def main(hexPasswords):
    querySetTrues = 0
    n = totalItems
    p = falsePositiveRate
    m, k = sizeFilter(n, p)

    print(f"Total items to be inserted: {n}\nFalse Positive Rate = {p}\nNumber of bits in array: {m}\nNumber of hash functions: {k}\n")
    

    bitArray = [0] * m                  # init bitArray with size m with zeros

    for i in range(n):
        insert(bitArray, m, k, hexPasswords[i])
        
    trainingSetTrues, trainingSetTime =  queryTime(m, k, n, hexPasswords, bitArray, offset=0)
    querySetTrues, querySetTime = queryTime(m, k, n, hexPasswords, bitArray, offset=450000)
            
    print(f"training trues: {trainingSetTrues} | AVG Time per 1000 queries: {trainingSetTime}ms\nquery trues: {querySetTrues} | AVG Time per 1000 queries: {querySetTime}ms")

if __name__ == "__main__":
    INPUT_FILE = 'processed_passwords.txt'

    hexPasswords = readData(INPUT_FILE)

    main(hexPasswords)
